Repository Simplon-hdf/corpo-event-grogneur-coupant, pull requests merged in 2025-01, with the labels that each got.

#7 docs(uml): modify the diagram of class
  doc/uml/diagramme-class.png
Labels: documentation

#8 docs(uml): update class diagram and add first sequence diagram
  doc/uml/diagramme-class.png
  doc/uml/diagramme-classe.png
  doc/uml/diagramme-sequence/creation-commentaire.png
Labels: documentation

#9 docs(uml): update sequence diagram 'creation-commentaire'
  doc/uml/diagramme-sequence/creation-commentaire.png
Labels: documentation

#10 docs(uml): add creation-evenement.png
  doc/uml/diagramme-sequence/creation-evenement.png
Labels: documentation

#11 docs(src): add src folder
  .gitignore
  README.md
  src/module-info.java
Labels: documentation

#12 docs(src): delete module-info.java
  src/Main.java
  src/module-info.java
Labels: documentation

#13 feat(src): add model and 3 class
  src/model/Collaborateur.java
  src/model/Commentaire.java
  src/model/Evenement.java
Labels: enhancement

#14 docs(uml): add role in Collaborateur class in class diagram
  doc/uml/diagramme-classe.png
Labels: documentation

#16 feat(src): add attribut in the evenement class
  doc/regles-gestion.md
  src/model/Evenement.java
Labels: documentation, enhancement

#15 docs(uml): add ids in relevant classes in class diagram
  doc/uml/diagramme-classe.png
Labels: documentation

#19 feat(src): update model and main classes
  src/Main.java
  src/main/Main.java
  src/repository/CommentaireRepository.java
Labels: enhancement

#21 docs(README.md): add the project readme
  README.md
Labels: documentation
